### ISSUE TITLE
Account-linker migration - the parachain side

### ISSUE THREAD

**Issue by h4n0** [litentry/integritee-node#3]
** Acceptance Criteria **

- [ ] ~~Modify the current account-linker to an interface between user and enclave~~
- [ ] ~~Integrate it into integritee-node~~
- [ ] ~~Account may need to reserve certain amount of LIT token to create an eth linking~~

The first two points aren't valid any more, due to the reuse of teerex for account linking. 

After [discussing](https://www.notion.so/litentry/TEE-Stakeholder-Requirements-bda39940be1f48eeb86664360b98e38d) with @hanwencheng and @qiuhaiguo , we won't carry out a reservation for account linking, only a transaction fee is sufficient here.

Therefore this epic is closed.
